# Nacos的配置文件copy
# dataId = muffle.yml
# group = DEV

muffle:
    # 权限相关
    security:
        token:
            secret: Jdk_18.com
            expired: 3600
            refresh-expired: 7200000
        un-check-url:
            - /test/**
            - /error
    
    
    
    # 路由限制
    way:
        ignore:
            clients: # 放行终端配置，网关不校验此处的终端
                - Auth
